const questions = [
    { text: "Social media influences people's opinions on world events.", type: "inference" },
    { text: "The latest smartphone model is always the best one.", type: "opinion" },
    { text: "Water freezes at 0°C under normal atmospheric conditions.", type: "fact" },
    { text: "Fast food is worse for your health than homemade meals.", type: "opinion" },
    { text: "The more followers you have on social media, the more successful you are.", type: "opinion" },
    { text: "If a new trend emerges online, it will become popular in real life.", type: "inference" },
    { text: "The average human heart beats around 100,000 times a day.", type: "fact" },
    { text: "Concerts are more fun than listening to music at home.", type: "opinion" },
    { text: "If a person stays up late every night, they may struggle with focus during the day.", type: "inference" },
    { text: "Streaming services have largely replaced DVDs and CDs.", type: "fact" },
    { text: "The latest blockbuster movie is better than any classic film.", type: "opinion" },
    { text: "If someone spends a lot of time at the gym, they are probably interested in fitness.", type: "inference" },
    { text: "The internet has changed how people communicate globally.", type: "fact" },
    { text: "Being popular in high school is important for future success.", type: "opinion" },
    { text: "If a person is constantly posting pictures from trips, they might enjoy traveling.", type: "inference" },
    { text: "A year has 365 days (except in leap years).", type: "fact" },
    { text: "Skateboarding is the coolest extreme sport.", type: "opinion" },
    { text: "If a person carries a lot of books, they might be a diligent student.", type: "inference" },
    { text: "Electric cars produce fewer emissions than gasoline-powered cars.", type: "fact" },
    { text: "Athletic brands make better sneakers than regular fashion brands.", type: "opinion" },
    { text: "If a person frequently uses emojis, they might be expressive when texting.", type: "inference" },
    { text: "The Earth has a molten core beneath its crust.", type: "fact" },
    { text: "Playing video games improves reaction time more than watching TV.", type: "opinion" },
    { text: "If someone spends hours practicing an instrument, they might be passionate about music.", type: "inference" },
    { text: "A person's diet affects their energy levels.", type: "fact" },
    { text: "The best way to relax after school is playing sports.", type: "opinion" },
    { text: "If someone never shares personal details online, they might be concerned about privacy.", type: "inference" },
    { text: "Gravity keeps planets in orbit around the Sun.", type: "fact" },
    { text: "Animated movies are more entertaining than live-action movies.", type: "opinion" },
    { text: "If a student always gets high grades, they might be academically gifted.", type: "inference" },
    { text: "Most smartphones rely on lithium-ion batteries.", type: "fact" },
    { text: "Being good at sports makes someone more attractive.", type: "opinion" },
    { text: "If a person never turns off their phone, they might rely on it a lot.", type: "inference" },
    { text: "Oceans cover around 70% of the Earth's surface.", type: "fact" },
    { text: "The best streaming service is the one with the most shows.", type: "opinion" },
    { text: "If a person listens to music every day, they likely enjoy it deeply.", type: "inference" },
    { text: "Bacteria can be both harmful and beneficial to humans.", type: "fact" },
    { text: "The latest gaming console is always better than its previous version.", type: "opinion" },
    { text: "If someone is constantly checking their notifications, they might be addicted to their phone.", type: "inference" },
    { text: "Most movie theaters use digital projectors instead of film reels.", type: "fact" },
    { text: "Street fashion is more stylish than designer brands.", type: "opinion" },
    { text: "If a person watches cooking videos often, they might enjoy learning new recipes.", type: "inference" },
    { text: "The Moon affects ocean tides on Earth.", type: "fact" },
    { text: "The best sport to play is basketball.", type: "opinion" },
    { text: "If a student brings their laptop everywhere, they might be tech-savvy.", type: "inference" },
    { text: "The human body is made up of around 60% water.", type: "fact" },
    { text: "Going to a party is always more fun than staying home.", type: "opinion" },
    { text: "If a person wears headphones most of the time, they might prefer avoiding distractions.", type: "inference" },
        { text: "Australia is the only country that is also a continent.", type: "fact" },
        { text: "Students who regularly review their lessons tend to perform better on tests.", type: "inference" },
        { text: "Shakespeare was one of the most influential writers in English literature.", type: "fact" },
        { text: "Decimals provide a more precise representation of numbers compared to fractions.", type: "inference" },
        { text: "Federation in 1901 united the Australian colonies into one country.", type: "fact" },
        { text: "Social media platforms have significantly shaped how teenagers interact and communicate.", type: "inference" },
        { text: "The Great Barrier Reef is one of the most diverse marine ecosystems in the world.", type: "fact" },
        { text: "People who do not engage in regular physical activity have a higher risk of health problems.", type: "inference" },
        { text: "The Pythagorean theorem applies to right-angled triangles.", type: "fact" },
        { text: "Creative writing allows for more personal expression than factual writing.", type: "inference" },
        { text: "The Sun appears to rise in the east and set in the west due to Earth’s rotation.", type: "fact" },
        { text: "Lack of sleep has been shown to negatively impact focus and cognitive function.", type: "inference" },
        { text: "The First Fleet arrived in Australia in 1788.", type: "fact" },
        { text: "Some students find science more engaging than other subjects due to its practical applications.", type: "inference" },
        { text: "Exposure to ultraviolet rays increases the risk of sunburn.", type: "fact" },
        { text: "Skipping breakfast can lead to lower energy levels later in the day.", type: "inference" },
        { text: "Rainforests contain the greatest biodiversity of any terrestrial ecosystem.", type: "fact" },
        { text: "Some artists believe that visual creativity has a strong impact on human emotion.", type: "inference" },
        { text: "The cells in your body divide to grow and repair tissues.", type: "fact" },
        { text: "Students who read often tend to develop a broader vocabulary.", type: "inference" },
        { text: "Australia has six states and two territories.", type: "fact" },
        { text: "Regular participation in sports can improve physical fitness and teamwork skills.", type: "inference" },
        { text: "Carbon dioxide emissions contribute to climate change.", type: "fact" },
        { text: "A diet high in processed foods is often associated with negative health effects.", type: "inference" },
        { text: "Shakespeare’s plays often explore themes of power and betrayal.", type: "fact" },
        { text: "Music has been found to influence mood and concentration in various studies.", type: "inference" },
        { text: "Convicts were transported to Australia by the British government.", type: "fact" },
        { text: "Digital learning tools can provide interactive ways to engage students in lessons.", type: "inference" },
        { text: "Countries with higher education rates tend to have stronger economies.", type: "fact" },
        { text: "The water cycle includes evaporation, condensation, and precipitation.", type: "fact" },
        { text: "Learning a second language has been shown to improve cognitive flexibility.", type: "inference" },
        { text: "Gravity keeps planets in orbit around the Sun.", type: "fact" },
        { text: "People who practice mathematics regularly tend to develop better problem-solving skills.", type: "inference" },
        { text: "Most smartphones rely on lithium-ion batteries.", type: "fact" },
        { text: "Individuals who engage in regular physical activity often have better overall health.", type: "inference" },
        { text: "Oceans cover around 70% of the Earth's surface.", type: "fact" },
        { text: "Exposure to natural environments has been linked to improved mental well-being.", type: "inference" },
        { text: "Bacteria can be both harmful and beneficial to humans.", type: "fact" },
        { text: "Students who engage in active study techniques tend to retain information more effectively.", type: "inference" },
        { text: "Most movie theaters use digital projectors instead of film reels.", type: "fact" },
        { text: "Physical activity has been shown to help reduce stress and anxiety levels.", type: "inference" },
        { text: "The Moon affects ocean tides on Earth.", type: "fact" },
        { text: "Hands-on learning methods can help students understand complex topics better.", type: "inference" },
        { text: "The human body is made up of around 60% water.", type: "fact" },
        { text: "Developing good study habits can improve academic performance.", type: "inference" },
        { text: "Computers process information using binary code.", type: "fact" },
        { text: "Students who learn coding often develop logical thinking skills.", type: "inference" },
        { text: "Plants use sunlight to make food through photosynthesis.", type: "fact" },
        { text: "Playing musical instruments is associated with improved memory and coordination.", type: "inference" }
    ];
    
