const questions = [
    { text: "Social media influences people's opinions on world events.", type: "inference" },
    { text: "The latest smartphone model is always the best one.", type: "opinion" },
    { text: "Water freezes at 0°C under normal atmospheric conditions.", type: "fact" },
    { text: "Fast food is worse for your health than homemade meals.", type: "opinion" },
    { text: "The more followers you have on social media, the more successful you are.", type: "opinion" },
    { text: "If a new trend emerges online, it will become popular in real life.", type: "inference" },
    { text: "The average human heart beats around 100,000 times a day.", type: "fact" },
    { text: "Concerts are more fun than listening to music at home.", type: "opinion" },
    { text: "If a person stays up late every night, they may struggle with focus during the day.", type: "inference" },
    { text: "Streaming services have largely replaced DVDs and CDs.", type: "fact" },
    { text: "The latest blockbuster movie is better than any classic film.", type: "opinion" },
    { text: "If someone spends a lot of time at the gym, they are probably interested in fitness.", type: "inference" },
    { text: "The internet has changed how people communicate globally.", type: "fact" },
    { text: "Being popular in high school is important for future success.", type: "opinion" },
    { text: "If a person is constantly posting pictures from trips, they might enjoy traveling.", type: "inference" },
    { text: "A year has 365 days (except in leap years).", type: "fact" },
    { text: "Skateboarding is the coolest extreme sport.", type: "opinion" },
    { text: "If a person carries a lot of books, they might be a diligent student.", type: "inference" },
    { text: "Electric cars produce fewer emissions than gasoline-powered cars.", type: "fact" },
    { text: "Athletic brands make better sneakers than regular fashion brands.", type: "opinion" },
    { text: "If a person frequently uses emojis, they might be expressive when texting.", type: "inference" },
    { text: "The Earth has a molten core beneath its crust.", type: "fact" },
    { text: "Playing video games improves reaction time more than watching TV.", type: "opinion" },
    { text: "If someone spends hours practicing an instrument, they might be passionate about music.", type: "inference" },
    { text: "A person's diet affects their energy levels.", type: "fact" },
    { text: "The best way to relax after school is playing sports.", type: "opinion" },
    { text: "If someone never shares personal details online, they might be concerned about privacy.", type: "inference" },
    { text: "Gravity keeps planets in orbit around the Sun.", type: "fact" },
    { text: "Animated movies are more entertaining than live-action movies.", type: "opinion" },
    { text: "If a student always gets high grades, they might be academically gifted.", type: "inference" },
    { text: "Most smartphones rely on lithium-ion batteries.", type: "fact" },
    { text: "Being good at sports makes someone more attractive.", type: "opinion" },
    { text: "If a person never turns off their phone, they might rely on it a lot.", type: "inference" },
    { text: "Oceans cover around 70% of the Earth's surface.", type: "fact" },
    { text: "The best streaming service is the one with the most shows.", type: "opinion" },
    { text: "If a person listens to music every day, they likely enjoy it deeply.", type: "inference" },
    { text: "Bacteria can be both harmful and beneficial to humans.", type: "fact" },
    { text: "The latest gaming console is always better than its previous version.", type: "opinion" },
    { text: "If someone is constantly checking their notifications, they might be addicted to their phone.", type: "inference" },
    { text: "Most movie theaters use digital projectors instead of film reels.", type: "fact" },
    { text: "Street fashion is more stylish than designer brands.", type: "opinion" },
    { text: "If a person watches cooking videos often, they might enjoy learning new recipes.", type: "inference" },
    { text: "The Moon affects ocean tides on Earth.", type: "fact" },
    { text: "The best sport to play is basketball.", type: "opinion" },
    { text: "If a student brings their laptop everywhere, they might be tech-savvy.", type: "inference" },
    { text: "The human body is made up of around 60% water.", type: "fact" },
    { text: "Going to a party is always more fun than staying home.", type: "opinion" },
    { text: "If a person wears headphones most of the time, they might prefer avoiding distractions.", type: "inference" }
            ];
    
